import bcrypt from "bcrypt";
const data = {
  users: [
    {
      name: "Nizar Maarouf",
      email: "nizar_maarouf@gmail.com",
      password: bcrypt.hashSync('1974', 8),
      isAdmin: true,
    },
    {
      name: "Adan",
      email: "Adan@gmail.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: false,
    }
  ],
  products: [
    {
      name: "بازل",
      category: " Games",
      image: "/images/product-1.jpg",
      price: 10,
      countInStock: 20,
      brand: "HADAYA",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "تيرموس نيروستا",
      category: "Bottles",
      image: "/images/product-2.jpg",
      price: 14,
      countInStock: 8,
      brand: "HADAYA",
      rating: 4.0,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "حامل مفاتيح",
      category: "Wood products",
      image: "/images/product-3.jpg",
      price: 5.5,
      countInStock: 7,
      brand: "HADAYA",
      rating: 4.8,
      numReviews: 17,
      description: "high quality product",
    },
    {
      name: "حقيبه للرحل والفعليات",
      category: "Bags",
      image: "/images/product-4.jpg",
      price: 5.5,
      countInStock: 15,
      brand: "HADAYA",
      rating: 4.5,
      numReviews: 14,
      description: "high quality product",
    },
    {
      name: "علبة الوان",
      category: "Colors Box",
      image: "/images/product-5.jpg",
      price: 11,
      countInStock: 11,
      brand: "HADAYA",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "كيس متعدد الاستعمالات",
      category: "Bags",
      image: "/images/product-6.jpg",
      price: 5.5,
      countInStock: 12,
      brand: "HADAYA",
      rating: 4.5,
      numReviews: 15,
      description: "high quality product",
    },
    {
      name: "قاعدة تلفون من خشب",
      category: "Wood products",
      image: "/images/product-7.jpg",
      price: 5.5,
      countInStock: 5,
      brand: "HADAYA",
      rating: 4.5,
      numReviews: 22,
      description: "high quality product",
    },
    {
      name: "قاعده للاشياء السخنه",
      category: "Wood products",
      image: "/images/product-8.jpg",
      price: 4,
      countInStock: 6,
      brand: "HADAYA",
      rating: 4.7,
      numReviews: 28,
      description: "high quality product",
    },
    {
      name: "قنينه للمياه البارده",
      category: "Bottle",
      image: "/images/product-9.jpg",
      price: 11,
      countInStock: 7,
      brand: "HADAYA",
      rating: 4.6,
      numReviews: 23,
      description: "high quality product",
    },
    {
      name: "كمامه للكبار",
      category: "Adult Masks",
      image: "/images/product-10.jpg",
      price: 8.5,
      countInStock: 22,
      brand: "HADAYA",
      rating: 4.2,
      numReviews: 28,
      description: "high quality product",
    },
    {
      name: "كمامه للاولاد",
      category: "Children Masks",
      image: "/images/product-11.jpg",
      price: 8.5,
      countInStock: 25,
      brand: "HADAYA",
      rating: 4.3,
      numReviews: 32,
      description: "high quality product",
    },
    {
      name: "كباي من معدن للاطفال",
      category: "Metal Cups",
      image: "/images/product-12.jpg",
      price: 10,
      countInStock: 14,
      brand: "HADAYA",
      rating: 4.5,
      numReviews: 27,
      description: "high quality product",
    },
    {
      name: "علبة طعام",
      category: "Food box",
      image: "/images/product-13.jpg",
      price: 10,
      countInStock: 2,
      brand: "HADAYA",
      rating: 4.7,
      numReviews: 50,
      description: "high quality product",
    },
    {
      name: "مراي مع صوره",
      category: "MirrorS",
      image: "/images/product-14.jpg",
      price: 8.5,
      countInStock: 17,
      brand: "HADAYA",
      rating: 4.0,
      numReviews: 19,
      description: "high quality product",
    },
    {
      name: "كبايات",
      category: "Cups",
      image: "/images/product-15.jpg",
      price: 10,
      countInStock: 3,
      brand: "HADAYA",
      rating: 4.6,
      numReviews: 26,
      description: "high quality product",
    },
    {
      name: "وساده",
      category: "Pillow",
      image: "/images/product-16.jpg",
      price: 14,
      countInStock: 4,
      brand: "HADAYA",
      rating: 4.8,
      numReviews: 45,
      description: "high quality product",
    },
    {
      name: "مقلمه",
      category: "Pencil case",
      image: "/images/product-17.jpg",
      price: 8.5,
      countInStock: 30,
      brand: "HADAYA",
      rating: 4.2,
      numReviews: 19,
      description: "high quality product",
    },
    {
      name: "مريول",
      category: "Apron",
      image: "/images/product-18.jpg",
      price: 8,
      countInStock: 27,
      brand: "HADAYA",
      rating: 4.9,
      numReviews: 35,
      description: "high quality product",
    },
    {
      name: "طقم طبخ",
      category: "Sets",
      image: "/images/product-19.jpg",
      price: 20,
      countInStock: 16,
      brand: "HADAYA",
      rating: 4.2,
      numReviews: 20,
      description: "high quality product",
    },
    {
      name: "طقم هديه مولود جديد",
      category: "Sets",
      image: "/images/product-20.jpg",
      price: 20,
      countInStock: 0,
      brand: "HADAYA",
      rating: 4.7,
      numReviews: 19,
      description: "high quality product",
    },
    {
      name: "طقم هديه مولود جديد",
      category: "Sets",
      image: "/images/product-21.jpg",
      price: 40,
      countInStock: 0,
      brand: "HADAYA",
      rating: 4.7,
      numReviews: 19,
      description: "high quality product",
    },
  ],
};

export default data;
